controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
ma_bibliotheque:
    path: /ma-bibliotheque
    controller: App\Controller\BibliothequeController::index

